---
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_default.yml"
    path: "bixby_default.yml"
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_rails_enabled.yml"
    path: "bixby_rails_enabled.yml"
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_rspec_enabled.yml"
    path: "bixby_rspec_enabled.yml"
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-50
    config:
      file: .rubocop.cc.yml
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
  - "**.coffee"
  - "**.rake"
  - "**.scss"
exclude_paths:
- config/
- vendor/
- .internal_test_app/
