inherit_gem:
  bixby: bixby_default.yml

inherit_from:
  - .rubocop.exceptions.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-batch_ingest.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/hyrax/batch_ingest/routing/batch_item_routes_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/services/batch_runner_spec.rb'

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/services/hyrax/batch_ingest/batch_runner.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/services/batch_runner_spec.rb'

Rails/OutputSafety:
  Exclude:
    - app/presenters/hyrax/batch_ingest/batch_presenter.rb
    - app/presenters/hyrax/batch_ingest/batch_item_presenter.rb
