Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-batch_ingest.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

RSpec/ExampleLength:
  Exclude:
    - 'lib/hyrax/batch_ingest/spec/shared_specs/batch_reader.rb'
    - 'spec/lib/hyrax/batch_ingest/routing/batch_item_routes_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/hyrax/batch_ingest/spec/shared_specs/*.rb'
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/services/batch_runner_spec.rb'

Rails/OutputSafety:
  Exclude:
    - app/presenters/hyrax/batch_ingest/batch_presenter.rb
    - app/presenters/hyrax/batch_ingest/batch_item_presenter.rb

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/services/hyrax/batch_ingest/batch_runner.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/services/batch_runner_spec.rb'
    - 'spec/jobs/batch_item_processing_job_spec.rb'

RSpec/NamedSubject:
  Exclude:
    - 'lib/hyrax/batch_ingest/spec/shared_specs/batch_item_ingester.rb'
    - 'lib/hyrax/batch_ingest/spec/shared_specs/batch_reader.rb'

RSpec/AnyInstance:
  Exclude:
    - 'lib/hyrax/batch_ingest/spec/shared_specs/batch_scanner.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'lib/hyrax/batch_ingest/spec/shared_specs/batch_scanner.rb'