---
ingest_types:
  example_ingest_type:
    label: "Example Ingest Type"
    reader: "ExampleReader"
    ingester: "ExampleIngester"
  other_ingest_type:
    label: "Other Ingest Type"
    reader: "OtherReader"
    ingester: "OtherIngester"
